# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://bitbucket.org/Healbe/healbe-public-ios-sdk.git'

target 'HealbeSDKSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HealbeSDKSample
  pod 'HealbeSDK'

end
